name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=15.2,name=iPhone 11 Pro']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        working-directory: SplunkRumWorkspace/
        run: |
          xcodebuild -workspace SplunkRumWorkspace.xcworkspace -scheme SmokeTest -destination "platform=iOS Simulator,OS=15.2,name=iPhone 11 Pro" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO > /dev/null
          zip ${GITHUB_WORKSPACE}/SmokeTest.zip $(find /Users/runner/Library/Developer/Xcode/DerivedData/SplunkRumWorkspace-dzmkiduinguystddyqrorblmaahj/Build/Products/Debug-iphonesimulator/SmokeTest.app -type f)
          ls /Users/runner/work/splunk-otel-ios/splunk-otel-ios
          pwd
          echo ${GITHUB_WORKSPACE}
      - name: uploading zip
        uses: actions/upload-artifact@v3
        with:
          name: SmokeTest
          path: /Users/runner/work/splunk-otel-ios/splunk-otel-ios/SmokeTest.zip
        env: 
         destination: ${{ matrix.destination }}
      - name: Test
        run: |
          xcodebuild clean test -project SmokeTest.xcodeproj -scheme SmokeTest -destination "platform=iOS Simulator,OS=15.2,name=iPhone 11 Pro" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
