name: CI-Test

on: [push]
jobs:
  full-build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Full Build
        run: ./fullbuild.sh
      - name: Smoke Test
        run: | 
          ./smoketest.sh 
          zip ${GITHUB_WORKSPACE}/SmokeTest.zip $(find /Users/runner/Library/Developer/Xcode/DerivedData/SplunkRumWorkspace/Build/Products/SplunkRumWorkspace-iphonesimulator/SmokeTest.app -type f)
          ls /Users/runner/work/splunk-otel-ios/splunk-otel-ios
          pwd
          echo ${GITHUB_WORKSPACE}
      - name: uploading zip
        uses: actions/upload-artifact@v3
        with:
          name: SmokeTest
          path: /Users/runner/work/splunk-otel-ios/splunk-otel-ios/SmokeTest.zip
      - name: Uploading app on sauce lab
        run: |
           cd /Users/runner/work/splunk-otel-ios/splunk-otel-ios/
           ls
           curl -u "sso-splunk.saucelabs.com-mahimag:274c9a94-86d1-4b12-9594-57307cfb2c57" --location \
             --request POST 'https://api.us-west-1.saucelabs.com/v1/storage/upload' \
             --form 'payload=@"SmokeTest.zip"' \
             --form 'name="SmokeTest.zip"' \
             --form 'description="iOS Test App v3"'
