name: CI-Test
on: [workflow_dispatch, push]
env:
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
jobs:
  full-build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Full Build
        run: ./fullbuild.sh
      - name: Smoke Test
        run: | 
         ./smoketest.sh 
      - name: uploading zip
        uses: actions/upload-artifact@v3
        with:
          name: SmokeTest
          path: /Users/runner/work/splunk-otel-ios/splunk-otel-ios/SmokeTest.zip
      - name: Uploading app on sauce lab
        run: |
           cd /Users/runner/work/splunk-otel-ios/splunk-otel-ios/
           ls
           curl -u "${{secrets.SAUCE_USERNAME}}:${{secrets.SAUCE_ACCESS_KEY}}" --location \
             --request POST 'https://api.us-west-1.saucelabs.com/v1/storage/upload' \
             --form 'payload=@"SmokeTest.zip"' \
             --form 'name="SmokeTest.zip"' \
             --form 'description="iOS Test App v3"'
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        working-directory: SplunkRumWorkspace
        run: |
            cd SmokeTest/
            python3 -m pip install Appium-Python-Client
            python3 test_appium.py
