name: Continuous Integration
on:
  push:
    branches: [Feature-APMI-1779-multiple-ios-versions]
  pull_request:

jobs:
  full-build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Full Build
        run: ./fullbuild.sh
      - name: Smoke Test
        run: ./smoketest.sh
